services:
  db:
    image: postgres:16
    container_name: go_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:secret@db:5432/go_api?sslmode=disable",
      "up"
    ]

  api:
    build: .
    container_name: go_gin_api
    restart: always
    depends_on:
      - db
      - migrate
    environment:
      DB_USER: postgres
      DB_PASS: secret
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: go_api
    ports:
      - "8000:8000"
    
volumes:
  pgdata:






